### ISSUE TITLE
Slow Down Item

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#77]
## Slow Down Item

From document:
>The game gets faster and faster while the character
is running.
If the player get’s a Slow Down Item (still to be
defined what icon to use), the speed slows down
25%, so the player can run for longer.

>This item should come just once in a while,
otherwise the game will be too easy.

**Comment by CarloAlbino** [comment]
I used up the spot for the slow down item for the spoon power-up.  The randomization didn't work properly when I had both power-ups in the same list.  This needs to be changed.

Also about the collider thing, maybe we can change them so they can only be picked up when you jump, and not when just running normally, just a thought.

**Comment by aytona** [comment]
So I have balanced it a bit to now not spawn the same air object over and over. Just a simple edit to take the previous object's name and not be able to spawn it next time. Collider edits will have to be on a different issue as it may require feedback from the rest of the team. But for now, this issue is done.
