### ISSUE TITLE
Make Game Scalable

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#86]
## Make Game Scalable
- Make the game look the same in 4:3 and 16:9 aspect ratio

**Comment by aytona** [comment]
Not sure if this issue is still needed or if its already fixed. But the Parent canvas should have a script attached to it that scales everything UI related.

As for player position and such, you can use the similar technique I used to position my warning signs.
It's mostly this portion of the script

> Vector3 worldPoint = Camera.main.ScreenToWorldPoint(new Vector3(Screen.width, 0, 0));
        Vector3 destination = new Vector3(worldPoint.x - xOffset, 0, 0);
        gameObject.transform.Translate(destination);
